// Generate src/audio/manifest.ts and src/audio/assets.ts from assets/samples.
import { readdirSync, writeFileSync } from 'node:fs';
const UNPITCHED = {
  bowl_1: ['bowl', 62.2], vibra_ring: ['bowl', 64.6],
  gong_soft: ['gong', 49.6], gong_55: ['gong', 42.8], gong_vibrant: ['gong', 42.8],
  cymbal_bow_1: ['texture'], cymbal_bow_2: ['texture'], ocean: ['bed'], breeze: ['bed'],
};
const files = readdirSync('assets/samples').filter((f) => f.endsWith('.mp3')).sort();
const rows = files.map((file) => {
  const id = file.replace('.mp3', '');
  const m = id.match(/^(bass|cello|viola|violin|flute)_(\d+)$/);
  if (m) return { id, kind: m[1], midi: Number(m[2]), file };
  const [kind, midi] = UNPITCHED[id] ?? [];
  if (!kind) throw new Error('unknown sample ' + id);
  return { id, kind, midi, file };
});
writeFileSync('src/audio/manifest.ts', `// Generated by scripts/manifest.mjs. Sources: VSCO 2 Community Edition (CC0) and
// Wikimedia Commons CC0 / public domain recordings. See assets/samples/CREDITS.md.
export type SampleKind = 'bass' | 'cello' | 'viola' | 'violin' | 'flute' | 'bowl' | 'gong' | 'texture' | 'bed';
export interface SampleDef { id: string; kind: SampleKind; midi?: number; file: string }
export const SAMPLES: ReadonlyArray<SampleDef> = [
${rows.map((r) => `  { id: '${r.id}', kind: '${r.kind}'${r.midi !== undefined ? `, midi: ${r.midi}` : ''}, file: '${r.file}' },`).join('\n')}
];
`);
writeFileSync('src/audio/assets.ts', `// Generated by scripts/manifest.mjs. Bundled sample assets, keyed by sample id.
export const SAMPLE_ASSETS: Record<string, number> = {
${rows.map((r) => `  ${r.id}: require('../../assets/samples/${r.file}'),`).join('\n')}
};
`);
console.log(rows.length, 'samples');
